# Generated by Django 4.2.4 on 2023-09-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('password', models.CharField()),
                ('address', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('img', models.ImageField(upload_to='media/')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerType', models.CharField(max_length=1)),
                ('identifyType', models.CharField(max_length=1)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('img', models.ImageField(upload_to='media/')),
                ('emergencyEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('hightSchoolName', models.CharField(max_length=100, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('totalScore', models.FloatField(max_length=255, null=True)),
                ('examCenter', models.CharField(max_length=100, null=True)),
                ('seat', models.CharField(max_length=20, null=True)),
                ('dateOfExamination', models.DateField(null=True)),
                ('countryName', models.CharField(max_length=100)),
                ('hightSchoolDiploma', models.ImageField(null=True, upload_to='media/')),
                ('hightSchoolTranscript', models.ImageField(null=True, upload_to='media/')),
                ('collegeName', models.CharField(max_length=100, null=True)),
                ('major', models.CharField(max_length=100, null=True)),
                ('credit', models.ImageField(null=True, upload_to='media/')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('examCertificate', models.ImageField(null=True, upload_to='media/')),
                ('englishProficiency', models.ImageField(null=True, upload_to='media/')),
                ('createAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('password', models.CharField()),
                ('address', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('emergencyName', models.CharField(max_length=100, null=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.register')),
            ],
        ),
    ]
