# Generated by Django 4.2.4 on 2023-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='credit',
            new_name='associateDegree',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='collegeName',
            new_name='majorReference',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='endDate',
            new_name='updateAt',
        ),
        migrations.RemoveField(
            model_name='register',
            name='countryName',
        ),
        migrations.RemoveField(
            model_name='register',
            name='englishProficiency',
        ),
        migrations.RemoveField(
            model_name='register',
            name='hightSchoolDiploma',
        ),
        migrations.RemoveField(
            model_name='register',
            name='hightSchoolTranscript',
        ),
        migrations.RemoveField(
            model_name='register',
            name='identifyType',
        ),
        migrations.RemoveField(
            model_name='register',
            name='major',
        ),
        migrations.RemoveField(
            model_name='register',
            name='registerType',
        ),
        migrations.RemoveField(
            model_name='register',
            name='startDate',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default=2023, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='gratuationYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='phoneNumber',
            field=models.CharField(default=2023, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
