# Generated by Django 4.2.4 on 2023-10-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_credit_register_associatedegree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='emergencyEmail',
            new_name='emergencyAddress',
        ),
        migrations.AddField(
            model_name='register',
            name='emergencyContactName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='emergencyContactRelationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='emergencyPhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
