# Generated by Django 4.2.4 on 2023-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_register_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gratuationYear',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
