# Generated by Django 4.2.4 on 2023-10-15 16:31

import MyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_register_gratuationyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='associateDegree',
            field=models.ImageField(null=True, upload_to=MyApp.models.UniqueFilename),
        ),
        migrations.AlterField(
            model_name='register',
            name='examCertificate',
            field=models.ImageField(null=True, upload_to=MyApp.models.UniqueFilename),
        ),
        migrations.AlterField(
            model_name='register',
            name='img',
            field=models.ImageField(upload_to=MyApp.models.UniqueFilename),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(upload_to=MyApp.models.UniqueFilename),
        ),
    ]
