# Generated by Django 4.2.4 on 2023-10-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_register_associatedegree_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
